// This file was generated by Prisma and assumes you have installed the following:

// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
// // Sur Vercel, les variables d'environnement sont déjà disponibles
// // Pas besoin de dotenv/config en production
// if (process.env.NODE_ENV !== 'production') {
//   require('dotenv').config();
// }
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: `tsx prisma/seed.ts`,
  },
  datasource: {
    url: process.env.DATABASE_URL || "", //env("DATABASE_URL"),
    shadowDatabaseUrl: process.env.DIRECT_URL || "", //env("DIRECT_URL"),
  },
});
